import Footer from '@/components/Footer';
import Navbar from '@/components/Navbar';
import { routing } from '@/i18n/routing';
import { adelphiSans, neueHaasUnicaW1GMono } from '@/lib/fonts';
import { hasLocale, NextIntlClientProvider } from 'next-intl';
import { notFound } from 'next/navigation';
import NextTopLoader from 'nextjs-toploader';
import '../../styles/globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children, params }) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={` ${adelphiSans.variable} ${neueHaasUnicaW1GMono.variable} antialiased`}>
        <NextIntlClientProvider>
          <NextTopLoader
            initialPosition={0.08}
            crawlSpeed={200}
            height={3}
            crawl={true}
            easing="ease"
            speed={200}
            shadow="0 0 10px #2299DD,0 0 5px #2299DD"
            color="var(--primary)"
            showSpinner={false}
          />
          <Navbar locale={locale} />
          {children}
          <Footer locale={locale} />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
